import "./globals.css";
import "../../public/styles/carousel.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Provider from "./utlis/Provider";
import ReactQueryClient from "./services/react-query-client";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html lang="en">
            <body className={inter.className}>
                <ReactQueryClient>
                    <Provider>{children}</Provider>
                </ReactQueryClient>
            </body>
        </html>
    );
}
